import { chromium, expect } from '@playwright/test';
import { mkdtemp, mkdir, rm, readFile, readdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { createReviewApp } from '../server/app.mjs';
import { checkSuggestionUI } from './suggestions-browser.mjs';
import { fixtureJson, fixtureProject } from './local-fixture.mjs';
import { checkRoleUI, checkActualRoleLayout } from './roles-browser.mjs';
import { checkReadingUI, checkActualReadingLayout } from './reading-browser.mjs';
import { checkHeadingImprovementsUI } from './heading-improvements-browser.mjs';
import { checkHeadingUI, checkActualHeadingLayout } from './headings-browser.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
process.env.CANDOC_BUILD_DIR ??= 'qa/browser-dist';
assert.notEqual(path.resolve(root, process.env.CANDOC_BUILD_DIR), path.join(root, 'dist'), 'browser tests must not overwrite user server static files');
await import('../scripts/build.mjs');
const originalPath = fixtureJson;
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const baseline = hash(await readFile(originalPath));
const temp = await mkdtemp(path.join(tmpdir(), 'candoc-ui-browser-'));
const dbPath = path.join(temp, 'review.sqlite');
await mkdir(path.join(root, 'qa'), { recursive: true });
let app = createReviewApp({ projectDir: fixtureProject, dbPath });
await new Promise(resolve => app.server.listen(0, '127.0.0.1', resolve));
const port = app.server.address().port;
const url = `http://127.0.0.1:${port}`;
let executablePath = process.env.CANDOC_BROWSER_EXECUTABLE;
if (!executablePath && process.platform === 'win32') {
  const cache = path.join(process.env.LOCALAPPDATA, 'ms-playwright');
  if (existsSync(cache)) {
    const candidates = (await readdir(cache)).filter(name => name.startsWith('chromium_headless_shell-')).sort((a, b) => Number(b.split('-').at(-1)) - Number(a.split('-').at(-1)));
    executablePath = candidates.map(name => path.join(cache, name, 'chrome-headless-shell-win64/chrome-headless-shell.exe')).find(existsSync);
  }
}
const browser = await chromium.launch({ headless: true, ...(executablePath ? { executablePath } : {}) });
const page = await browser.newPage({ viewport: { width: 1512, height: 982 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
const decision = page.getByRole('region', { name: /원본 \d+페이지 판단/ });
const stageButton = id => page.locator(`[data-stage-id="${id}"]`);
const tile = (number, status) => page.getByRole('button', { name: `원본 ${number}페이지 · ${status}`, exact: true });
const state = async () => (await fetch(url + '/api/review')).json();
try {
  await page.goto(url);
  await expect(page.getByRole('heading', { name: '불필요한 페이지 선별' })).toBeVisible();
  await expect(page.locator('.step')).toHaveCount(11);
  await expect(page.locator('.step-completed')).toHaveCount(0);
  await expect(page.getByRole('button', { name: '나머지 유지하고 완료', exact: true })).toBeEnabled();
  assert.ok((await state()).decisions.every(page => page.status === 'unreviewed'));
  await expect(decision).toHaveCount(0);
  await expect(page.locator('.tile-main')).toHaveCount(138);
  await expect(page.getByRole('button', { name: /페이지 묶음/ })).toHaveCount(0);
  await page.waitForFunction(() => [...document.querySelectorAll('.page-tile img')].slice(0, 4).every(img => img.complete && img.naturalWidth > 0));
  const auditText = async () => page.evaluate(() => {
    const luminance = color => {
      const values = color.match(/[\d.]+/g).slice(0, 3).map(Number).map(value => value / 255).map(value => value <= .04045 ? value / 12.92 : ((value + .055) / 1.055) ** 2.4);
      return .2126 * values[0] + .7152 * values[1] + .0722 * values[2];
    };
    return ['.page-heading p', '.step-pending', '.counts', '.bulk-toolbar strong', '.tile-caption strong', '.scroll-summary', '.tile-excluded .tile-caption span', '.tile-included .tile-caption span', '.tile-pending .tile-caption span'].filter(selector => document.querySelector(selector)).map(selector => {
      const element = document.querySelector(selector), style = getComputedStyle(element);
      let ancestor = element, background;
      while (ancestor) {
        background = getComputedStyle(ancestor).backgroundColor;
        if (background !== 'rgba(0, 0, 0, 0)' && background !== 'transparent') break;
        ancestor = ancestor.parentElement;
      }
      const levels = [luminance(style.color), luminance(background)].sort((a, b) => b - a);
      return { selector, fontSize: parseFloat(style.fontSize), contrast: (levels[0] + .05) / (levels[1] + .05) };
    });
  });
  for (const text of await auditText()) {
    assert.ok(text.fontSize >= 12, `${text.selector} must remain readable`);
    assert.ok(text.contrast >= 4.5, `${text.selector} light-theme contrast: ${text.contrast}`);
  }
  await expect(page.getByLabel('원본 페이지 번호 검색')).toHaveCSS('height', '36px');
  await expect(page.getByLabel('페이지 상태 필터')).toHaveCSS('height', '36px');
  assert.ok((await page.locator('.page-sheet').first().boundingBox()).y < 260, 'desktop controls must leave space for pages');
  await page.screenshot({ path: path.join(root, 'qa/desktop.png') });
  const infoButton = page.getByRole('button', { name: '문서 정보', exact: true });
  await infoButton.click();
  await expect(page.getByRole('heading', { name: '문서 정보', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: /완료 기록/ })).toHaveCount(0);
  await expect(page.locator('#stage-note')).toHaveCount(0);
  await expect(page.locator('.process-title')).toContainText('0 / 11');
  await expect(page.locator('.document-facts > div').filter({ hasText: '문서 스키마 버전' })).toContainText('1.10.0');
  await expect(page.locator('.document-facts > div').filter({ hasText: '변환 프로그램 버전' })).toContainText('알 수 없음');
  await expect(page.locator('.document-facts')).toContainText('IEEE-1547-2018.pdf');
  await expect(page.getByRole('button', { name: /대상과 범위 확인|기본 무결성/ })).toHaveCount(0);
  await page.screenshot({ path: path.join(root, 'qa/document-info.png') });
  await page.setViewportSize({ width: 375, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'document info must fit mobile width');
  await expect(page.getByRole('button', { name: '페이지 선별로 이동', exact: true })).toBeEnabled();
  await page.screenshot({ path: path.join(root, 'qa/document-info-mobile.png') });
  await page.setViewportSize({ width: 1512, height: 982 });
  await page.reload();
  await expect(page.getByRole('heading', { name: '문서 정보', exact: true })).toBeVisible();
  await page.route('**/api/document', async route => {
    const response = await route.fetch();
    const document = await response.json();
    await route.fulfill({ json: { ...document, originalFile: 'a'.repeat(240) + '.pdf', schemaVersion: '1.11.0', input: { ...document.input, versionConfirmed: false, missingImages: [2] } } });
  });
  await page.reload();
  await expect(page.locator('.impact-banner').filter({ hasText: '1.11.0' })).toContainText('페이지 선별은 계속할 수 있습니다');
  await expect(page.locator('.impact-banner').filter({ hasText: '원문 이미지가 없는 페이지' })).toContainText('JSON을 근거로 검수');
  await page.setViewportSize({ width: 320, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'long original filename must wrap inside document info');
  await page.setViewportSize({ width: 1512, height: 982 });
  await page.getByRole('button', { name: '페이지 선별로 이동', exact: true }).click();
  await expect(page.locator('.tile-main')).toHaveCount(138);
  await page.unroute('**/api/document');
  await page.reload();
  await tile(1, '미검수').click();
  await expect(tile(1, '미검수')).toHaveAttribute('aria-pressed', 'true');
  await tile(2, '미검수').click();
  await expect(tile(1, '미검수')).toHaveAttribute('aria-pressed', 'true');
  await expect(tile(2, '미검수')).toHaveAttribute('aria-pressed', 'true');
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('2페이지 선택');
  await tile(1, '미검수').click();
  await expect(tile(1, '미검수')).toHaveAttribute('aria-pressed', 'false');
  await expect(tile(2, '미검수')).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('checkbox', { name: '원본 3페이지 선택', exact: true }).click();
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('2페이지 선택');
  await page.reload();
  await expect(tile(2, '미검수')).toHaveAttribute('aria-pressed', 'true');
  await expect(tile(3, '미검수')).toHaveAttribute('aria-pressed', 'true');
  assert.deepEqual((await state()).selectedPages, [2, 3]);
  await tile(3, '미검수').click();
  await expect(tile(3, '미검수')).toHaveAttribute('aria-pressed', 'false');
  await expect(tile(2, '미검수')).toHaveAttribute('aria-pressed', 'true');
  await tile(2, '미검수').click();
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('0페이지 선택');
  await tile(1, '미검수').dblclick();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('dialog').getByRole('img')).toHaveAttribute('src', '/api/pages/1/image');
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await expect(decision).toHaveCount(0);
  await page.getByRole('button', { name: '상세 패널 열기', exact: true }).click();
  await expect(decision.getByRole('img')).toBeVisible();
  await decision.getByRole('radio', { name: '제외', exact: true }).check();
  await expect(decision.getByRole('button', { name: '판단 저장', exact: true })).toBeDisabled();
  await page.locator('#page-reason').fill('브라우저 테스트의 제외 사유');
  await page.locator('#page-note').fill('재시작 후에도 남아야 하는 메모');
  await decision.getByRole('button', { name: '판단 저장', exact: true }).click();
  await expect(decision.getByText('저장: 제외', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.locator('#page-reason')).toHaveValue('브라우저 테스트의 제외 사유');
  await expect(page.locator('#page-note')).toHaveValue('재시작 후에도 남아야 하는 메모');

  await tile(2, '미검수').click();
  await expect(decision.getByText('원본 2페이지', { exact: true })).toBeVisible();
  await decision.getByRole('radio', { name: '포함', exact: true }).check();
  await page.locator('#page-reason').fill('이 초안은 취소되어야 함');
  await tile(3, '미검수').click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByRole('button', { name: '현재 화면 유지', exact: true }).click();
  await expect(page.locator('#page-reason')).toHaveValue('이 초안은 취소되어야 함');
  assert.equal((await state()).decisions.find(item => item.page === 2).status, 'unreviewed');
  await tile(3, '미검수').click();
  await page.getByRole('button', { name: '초안 취소 후 이동', exact: true }).click();
  await expect(decision.getByText('원본 3페이지', { exact: true })).toBeVisible();
  assert.equal((await state()).decisions.find(item => item.page === 2).status, 'unreviewed');
  await decision.getByRole('radio', { name: '포함', exact: true }).check();
  await page.locator('#page-note').fill('저장 후 이동 동작 확인');
  await tile(4, '미검수').click();
  await page.getByRole('button', { name: '저장 후 이동', exact: true }).click();
  await expect(decision.getByText('원본 4페이지', { exact: true })).toBeVisible();
  assert.equal((await state()).decisions.find(item => item.page === 3).note, '저장 후 이동 동작 확인');

  await stageButton(6).click();
  await page.locator('#stage-note').fill('브라우저 테스트: 영역과 역할 확인의 수동 검토 근거');
  await page.getByRole('button', { name: '수동 검토 완료 기록', exact: true }).click();
  await expect(stageButton(6)).toHaveClass(/step-completed/);
  await stageButton(5).click();
  await expect(stageButton(5)).toHaveClass(/step-current/);
  await expect(stageButton(5)).not.toHaveClass(/step-completed/);
  await page.reload();
  await expect(stageButton(5)).toHaveClass(/step-current/);
  await expect(stageButton(6)).toHaveClass(/step-completed/);

  await page.goto('about:blank');
  await app.close();
  app = createReviewApp({ projectDir: fixtureProject, dbPath });
  await new Promise(resolve => app.server.listen(port, '127.0.0.1', resolve));
  await page.goto(url);
  await expect(stageButton(5)).toHaveClass(/step-current/);
  await expect(stageButton(6)).toHaveClass(/step-completed/);
  await stageButton(6).click();
  await expect(page.locator('#stage-note')).toHaveValue('브라우저 테스트: 영역과 역할 확인의 수동 검토 근거');
  await stageButton(2).click();
  await tile(1, '제외').click();
  await expect(page.locator('#page-note')).toHaveValue('재시작 후에도 남아야 하는 메모');
  await decision.getByRole('radio', { name: '포함', exact: true }).check();
  await page.locator('#page-reason').fill('제외 취소 및 복원 확인');
  await decision.getByRole('button', { name: '판단 저장', exact: true }).click();
  await expect(tile(1, '포함')).toBeVisible();

  await page.getByRole('button', { name: 'JSON 텍스트 보기', exact: true }).click();
  await expect(page.locator('.json-text')).toContainText('#/texts/');
  await page.getByRole('button', { name: 'JSON 텍스트 닫기', exact: true }).click();
  await page.getByRole('button', { name: '이미지 크게 보기 ↗', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);

  await page.getByLabel('페이지 상태 필터').selectOption('pending');
  await expect(page.getByText('이 조건에 해당하는 페이지가 없습니다.', { exact: true })).toBeVisible();
  await page.getByLabel('페이지 상태 필터').selectOption('all');
  await page.getByRole('textbox', { name: '원본 페이지 번호 검색', exact: true }).fill('138');
  await tile(138, '미검수').click();
  await expect(decision.getByRole('img')).toHaveAttribute('src', '/api/pages/138/image');
  await page.getByRole('textbox', { name: '원본 페이지 번호 검색', exact: true }).fill('');

  await page.getByRole('button', { name: '상세 패널 닫기', exact: true }).click();
  await expect(decision).toHaveCount(0);
  const displaySlider = page.getByRole('slider', { name: '페이지 썸네일 크기', exact: true });
  await displaySlider.focus(); await page.keyboard.press('Home');
  await expect(displaySlider).toHaveValue('120');
  await expect(page.locator('.tile-main')).toHaveCount(138);
  await expect(page.locator('.page-gallery')).toHaveCSS('--thumbnail-size', '120px');
  await page.getByRole('button', { name: '선택 취소', exact: true }).click();
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('0페이지 선택');
  await tile(8, '미검수').click();
  await tile(1, '포함').click();
  await tile(4, '미검수').click({ modifiers: ['Shift'] });
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('5페이지 선택');
  await expect(tile(8, '미검수')).toHaveAttribute('aria-pressed', 'true');
  await tile(6, '미검수').click({ modifiers: ['Shift'] });
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('7페이지 선택');
  await tile(8, '미검수').click();
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('6페이지 선택');
  assert.deepEqual((await state()).selectedPages, [1, 2, 3, 4, 5, 6]);
  await tile(3, '포함').click({ modifiers: ['Control'] });
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('5페이지 선택');
  await page.getByRole('checkbox', { name: '원본 3페이지 선택', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: '원본 3페이지 선택', exact: true })).toBeChecked();
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('6페이지 선택');
  await page.getByRole('button', { name: '일괄 제외', exact: true }).click();
  await expect(page.getByRole('button', { name: '6페이지 제외 저장', exact: true })).toBeDisabled();
  await page.locator('#bulk-reason').fill('범위 선택 일괄 제외 검증');
  await page.locator('#bulk-note').fill('모든 선택 페이지에 같은 근거 저장');
  await page.getByRole('button', { name: '6페이지 제외 저장', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  assert.ok((await state()).decisions.slice(0, 6).every(item => item.status === 'excluded' && item.reason === '범위 선택 일괄 제외 검증'));
  await expect(page.locator('.exclusion-stamp')).toHaveCount(6);
  await page.reload();
  await expect(decision).toHaveCount(0);
  await expect(page.locator('.tile-main')).toHaveCount(138);
  await expect(displaySlider).toHaveValue('120');
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('6페이지 선택');
  await page.getByRole('button', { name: '일괄 포함', exact: true }).click();
  await page.locator('#bulk-reason').fill('일괄 제외 취소');
  await page.getByRole('button', { name: '6페이지 포함 저장', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  assert.ok((await state()).decisions.slice(0, 6).every(item => item.status === 'included'));
  await expect(page.locator('.exclusion-stamp')).toHaveCount(0);
  await displaySlider.focus(); await page.keyboard.press('End');
  await expect(displaySlider).toHaveValue('360');
  await expect(page.locator('.tile-main')).toHaveCount(138);
  await expect(page.locator('.page-gallery')).toHaveCSS('--thumbnail-size', '360px');
  await page.reload();
  await expect(displaySlider).toHaveValue('360');
  await expect(page.locator('.tile-main')).toHaveCount(138);
  await tile(138, '미검수').scrollIntoViewIfNeeded();
  await expect(tile(138, '미검수')).toBeInViewport();
  await page.waitForFunction(() => { const image = document.querySelector('img[src="/api/pages/138/image"]'); return image?.complete && image.naturalWidth > 0; });
  await page.screenshot({ path: path.join(root, 'qa/scroll-end.png') });
  await page.getByRole('button', { name: '선택 취소', exact: true }).click();
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('0페이지 선택');
  await tile(1, '포함').click();
  await tile(40, '미검수').click({ modifiers: ['Shift'] });
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('40페이지 선택');
  assert.deepEqual((await state()).selectedPages, Array.from({ length: 40 }, (_, index) => index + 1));
  await page.getByRole('button', { name: '일괄 제외', exact: true }).click();
  await page.locator('#bulk-reason').fill('기존 36페이지 제한을 넘는 범위 일괄 제외');
  await page.getByRole('button', { name: '40페이지 제외 저장', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  assert.ok((await state()).decisions.slice(0, 40).every(item => item.status === 'excluded'));
  await page.getByRole('button', { name: '일괄 포함', exact: true }).click();
  await page.getByRole('button', { name: '40페이지 포함 저장', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: '목록 전체 선택', exact: true }).click();
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('138페이지 선택');
  await page.getByRole('button', { name: '선택 취소', exact: true }).click();
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('0페이지 선택');
  await page.getByLabel('페이지 상태 필터').selectOption('included');
  await expect(page.locator('.tile-main')).toHaveCount(40);
  await page.getByRole('button', { name: '목록 전체 선택', exact: true }).click();
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('40페이지 선택');
  assert.ok((await state()).selectedPages.every(number => number <= 40));
  await page.getByLabel('페이지 상태 필터').selectOption('all');
  await expect(page.locator('.tile-main')).toHaveCount(138);
  await tile(20, '포함').dblclick();
  await expect(page.getByRole('dialog').getByRole('img')).toHaveAttribute('src', '/api/pages/20/image');
  await page.keyboard.press('Escape');
  assert.equal((await state()).selectedPage, 20);
  assert.deepEqual((await state()).selectedPages, Array.from({ length: 40 }, (_, index) => index + 1).filter(number => number !== 20));
  await expect(decision).toHaveCount(0);

  await page.getByRole('button', { name: '선택 취소', exact: true }).click();
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('0페이지 선택');
  await tile(1, '포함').click();
  await tile(4, '포함').click({ modifiers: ['Shift'] });
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('4페이지 선택');
  await page.getByRole('button', { name: '일괄 제외', exact: true }).click();
  await page.locator('#bulk-reason').fill('앞부분 불필요한 페이지를 제외하고 나머지는 유지');
  await page.getByRole('button', { name: '4페이지 제외 저장', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.locator('.exclusion-stamp')).toHaveCount(4);
  await expect(tile(1, '제외').locator('.exclusion-stamp')).toBeVisible();
  await expect(tile(1, '제외').locator('.exclusion-stamp')).toHaveText('제외됨');
  await page.locator('.page-heading').scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(root, 'qa/excluded-pages.png') });
  const beforeComplete = await state();
  await page.getByRole('button', { name: '선택 취소', exact: true }).click();
  await expect(page.locator('.bulk-toolbar strong')).toHaveText('0페이지 선택');
  await page.getByLabel('페이지 상태 필터').selectOption('excluded');
  await expect(page.locator('.tile-main')).toHaveCount(4);
  await page.getByRole('button', { name: '나머지 유지하고 완료', exact: true }).click();
  await expect(stageButton(2)).toHaveClass(/step-completed/);
  const finished = await state();
  assert.deepEqual(finished.decisions.slice(0, 40), beforeComplete.decisions.slice(0, 40));
  assert.ok(finished.decisions.slice(40).every(page => page.status === 'included' && page.evidence === 'selection'));
  assert.deepEqual(finished.selectedPages, []);
  await page.reload();
  await expect(stageButton(2)).toHaveClass(/step-completed/);
  await expect(page.locator('.exclusion-stamp')).toHaveCount(4);
  await page.goto('about:blank');
  await app.close();
  app = createReviewApp({ projectDir: fixtureProject, dbPath });
  await new Promise(resolve => app.server.listen(port, '127.0.0.1', resolve));
  await page.goto(url);
  await expect(stageButton(2)).toHaveClass(/step-completed/);
  await expect(page.locator('.exclusion-stamp')).toHaveCount(4);
  assert.deepEqual((await state()).decisions, finished.decisions);
  await page.getByLabel('페이지 상태 필터').selectOption('all');
  await tile(138, '포함').dblclick();
  await expect(page.getByRole('dialog').getByRole('img')).toHaveAttribute('src', '/api/pages/138/image');
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '상세 패널 열기', exact: true }).click();
  await expect(page.locator('#page-evidence')).toHaveValue('selection');
  await decision.getByRole('radio', { name: '보류', exact: true }).check();
  await page.locator('#page-reason').fill('선별 완료 후 추가 확인이 필요한 페이지');
  await expect(decision.getByRole('button', { name: '판단 저장', exact: true })).toBeDisabled();
  await page.locator('#page-evidence').selectOption('json');
  await decision.getByRole('button', { name: '판단 저장', exact: true }).click();
  await expect(page.getByRole('button', { name: '페이지 선별 완료 기록', exact: true })).toBeDisabled();
  assert.equal((await state()).decisions.find(page => page.page === 138).status, 'pending');
  await decision.getByRole('radio', { name: '포함', exact: true }).check();
  await decision.getByRole('button', { name: '판단 저장', exact: true }).click();
  await page.getByRole('button', { name: '페이지 선별 완료 기록', exact: true }).click();
  await expect(stageButton(2)).toHaveClass(/step-completed/);
  await page.getByRole('button', { name: '상세 패널 닫기', exact: true }).click();
  await page.locator('.page-heading').scrollIntoViewIfNeeded();

  for (const [width, filename] of [[1024, 'tablet.png'], [375, 'mobile.png'], [320, 'narrow.png']]) {
    await page.setViewportSize({ width, height: 900 });
    if (width < 630) {
      await expect(page.getByRole('button', { name: '검수 과정 보기', exact: true })).toHaveAttribute('aria-expanded', 'false');
      await expect(page.locator('.steps')).not.toBeVisible();
      await expect(tile(1, '제외')).toBeInViewport();
      await page.getByRole('button', { name: '검수 과정 보기', exact: true }).press('Enter');
      await expect(page.locator('.steps')).toBeVisible();
      await expect(page.locator('.step')).toHaveCount(11);
      await page.getByRole('button', { name: '검수 과정 접기', exact: true }).click();
      await expect(page.locator('.steps')).not.toBeVisible();
      if (width === 375) {
        await page.getByRole('button', { name: '검수 과정 보기', exact: true }).click();
        await stageButton(5).click();
        await expect(page.getByRole('heading', { name: '제목과 문서 개요', exact: true })).toBeVisible();
        await expect(page.locator('.steps')).not.toBeVisible();
        await page.getByRole('button', { name: '검수 과정 보기', exact: true }).click();
        await stageButton(2).click();
        await expect(page.getByRole('heading', { name: '불필요한 페이지 선별', exact: true })).toBeVisible();
        await expect(page.locator('.steps')).not.toBeVisible();
        await expect(stageButton(2)).toHaveClass(/step-completed/);
      }
    }
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `horizontal overflow at ${width}px`);
    await page.screenshot({ path: path.join(root, 'qa', filename), fullPage: false });
  }
  await page.setViewportSize({ width: 1512, height: 982 });
  const touchPage = await browser.newPage({ viewport: { width: 375, height: 844 }, isMobile: true, hasTouch: true });
  await touchPage.goto(url);
  await expect(touchPage.getByRole('button', { name: '검수 과정 보기', exact: true })).toHaveAttribute('aria-expanded', 'false');
  await expect(touchPage.locator('.steps')).not.toBeVisible();
  await expect(touchPage.getByRole('button', { name: '원본 1페이지 · 제외', exact: true })).toBeInViewport();
  for (const target of [touchPage.getByLabel('원본 페이지 번호 검색'), touchPage.getByLabel('페이지 상태 필터'), touchPage.getByRole('button', { name: '검수 과정 보기', exact: true }), touchPage.locator('.tile-checkbox').first()]) {
    const bounds = await target.boundingBox();
    assert.ok(bounds.width >= 44 && bounds.height >= 44, 'mobile controls need enough touch space');
  }
  assert.ok(await touchPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'horizontal overflow in touch mode');
  await touchPage.screenshot({ path: path.join(root, 'qa/mobile-touch.png') });
  await touchPage.close();
  await page.emulateMedia({ colorScheme: 'dark' });
  await expect(page.locator('.step-current')).toHaveCSS('background-color', 'rgb(33, 51, 38)');
  for (const text of await auditText()) assert.ok(text.contrast >= 4.5, `${text.selector} dark-theme contrast: ${text.contrast}`);
  await page.locator('.page-heading').scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(root, 'qa/dark.png') });
  await page.getByRole('button', { name: '밝은 테마', exact: true }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  await expect(page.locator('.step-current')).toHaveCSS('background-color', 'rgb(237, 245, 238)');
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  await expect(page.locator('.step-current')).toHaveCSS('background-color', 'rgb(237, 245, 238)');
  await page.getByRole('button', { name: '어두운 테마', exact: true }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await expect(page.locator('.step-current')).toHaveCSS('background-color', 'rgb(33, 51, 38)');
  await infoButton.click();
  await expect(page.getByRole('heading', { name: '문서 정보', exact: true })).toBeVisible();
  await page.screenshot({ path: path.join(root, 'qa/document-info-dark.png') });
  await stageButton(2).click();
  await mkdir(path.join(temp, 'raw'), { recursive: true });
  const invalidPath = path.join(temp, 'raw/invalid-document.json');
  await writeFile(invalidPath, '{invalid JSON');
  const invalidApp = createReviewApp({ jsonPath: invalidPath, dbPath: path.join(temp, 'invalid-review.sqlite') });
  await new Promise(resolve => invalidApp.server.listen(0, '127.0.0.1', resolve));
  const invalidPage = await browser.newPage();
  const invalidErrors = [];
  invalidPage.on('pageerror', error => invalidErrors.push(error.message));
  try {
    await invalidPage.goto(`http://127.0.0.1:${invalidApp.server.address().port}`);
    await expect(invalidPage.getByRole('alert')).toContainText('입력 파일을 JSON으로 읽을 수 없습니다');
    await expect(invalidPage.getByRole('button', { name: '다시 불러오기', exact: true })).toBeVisible();
    assert.deepEqual(invalidErrors, []);
    assert.equal(existsSync(path.join(temp, 'invalid-review.sqlite')), false);
  } finally { await invalidPage.close(); await invalidApp.close(); }
  await checkSuggestionUI(browser);
  await (await import('./project-codex-settings-browser.mjs')).checkProjectCodexSettingsUI(browser);
  await checkRoleUI(browser);
  await (await import('./role-questions-browser.mjs')).checkRoleQuestionsUI(browser);
  const annotations = await import('./role-annotations-browser.mjs'); await annotations.checkRoleAnnotationsUI(browser); await annotations.checkActualAnnotationLayout(browser);
  await (await import('./annotation-input-browser.mjs')).checkActualAnnotationInputUI(browser);
  await checkActualRoleLayout(browser);
  await checkReadingUI(browser);
  await checkActualReadingLayout(browser);
  await checkHeadingUI(browser); await checkHeadingImprovementsUI(browser);
  await checkActualHeadingLayout(browser);
  assert.deepEqual(errors, []);
  assert.equal(hash(await readFile(originalPath)), baseline);
  console.log('Browser checks passed: document info without completion or notes, 11 review steps, schema/converter versions distinguished, unverified version and missing-image guidance, document-info mobile/dark layouts, unusable input error screen without DB writes, readable text contrast, shared control sizes, collapsed mobile process, keep remaining pages and finish, exclusion stamps/restoration, pending gate, reload/restart persistence, independent toggles, additive Shift range, all 138 pages, 40-page bulk decisions, filtering, zoom, drafts, source image/text, hidden panel, double-click, 1512/1024/375/320px, theme persistence. Test DB was isolated from project review records.');
} finally {
  await browser.close(); await app.close();
  assert.equal(path.dirname(temp), path.resolve(tmpdir()));
  assert.ok(path.basename(temp).startsWith('candoc-ui-browser-'));
  await rm(temp, { recursive: true, force: true });
}
