import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import type { HeadingDraft } from '@/types';
import { ProjectCodexLink, useProjectCodex } from './project-codex-settings';
type Group = { id: string; reason: string; changes: { ref: string; before: HeadingDraft; after: HeadingDraft }[] };
type Job = { id: string; status: string; revision: number; stale: boolean; suggestions: Group[]; error?: string };
export function HeadingSuggestions({ revision, dirty, onLocate, onApprove }: { revision: number; dirty: boolean; onLocate: (ref: string) => void; onApprove: (items: HeadingDraft[]) => void }) {
  const { state: { settings: { model, effort } } } = useProjectCodex();
  const [job, setJob] = useState<Job | null>(null), [error, setError] = useState(''), [exceptions, setExceptions] = useState<Record<string, string[]>>({});
  async function call(url: string, method = 'GET', body?: object) { const response = await fetch(url, { method, ...(body ? { headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : {}) }); const value = await response.json(); if (!response.ok) throw Error(value.error); return value; }
  useEffect(() => { void call('/api/review/heading-suggestions').then(setJob).catch(e => setError(e.message)); }, [revision]);
  useEffect(() => { if (job?.status !== 'running') return; const timer = window.setInterval(() => { void call('/api/review/heading-suggestions').then(setJob).catch(e => setError(e.message)); }, 700); return () => clearInterval(timer); }, [job?.status]);
  async function request() { setError(''); try { setJob(await call('/api/review/heading-suggestions', 'POST', { revision, model, effort })); setExceptions({}); } catch (e) { setError((e as Error).message); } }
  async function approve(group: Group) { setError(''); try { const value = await call('/api/review/heading-suggestions/preview', 'POST', { id: job!.id, groupId: group.id, revision, exceptions: exceptions[group.id] ?? [] }); onApprove(value.items); } catch (e) { setError((e as Error).message); } }
  return <details className="heading-agent"><summary>에이전트 추천{job?.status === 'running' ? ' · 생성 중' : ''}</summary><div className="heading-toolbar"><ProjectCodexLink /><Button size="sm" disabled={dirty || !model || !effort || job?.status === 'running'} onClick={() => void request()}>목차 추천 요청</Button>{job?.status === 'running' && <Button size="sm" variant="outline" onClick={() => void call('/api/review/heading-suggestions', 'DELETE', { id: job.id }).then(setJob).catch(e => setError(e.message))}>제목 추천 취소</Button>}</div>
    <p>추천은 의심과 변경안입니다. 승인하면 초안에만 반영하고 별도 저장·검수 확인이 필요합니다.{dirty ? ' 기존 초안을 먼저 저장하거나 취소하세요.' : ''}</p>{(error || job?.error) && <p role="alert">{error || job?.error}</p>}{job?.stale && <p>검수 버전이 바뀐 추천입니다. 새 추천을 요청하세요.</p>}{job?.status === 'completed' && !job.suggestions.length && <p>추천 항목이 없습니다. 오류가 없다는 뜻은 아닙니다.</p>}
    {job?.suggestions.map(group => <details key={group.id}><summary>{group.reason} · 대상 {group.changes.length}개 / 예외 {(exceptions[group.id] ?? []).length}개</summary>{group.changes.map(change => <div className="heading-recommendation" key={change.ref}><label><input type="checkbox" aria-label={`${change.ref} 추천 대상`} checked={!(exceptions[group.id] ?? []).includes(change.ref)} onChange={event => setExceptions({ ...exceptions, [group.id]: event.target.checked ? (exceptions[group.id] ?? []).filter(ref => ref !== change.ref) : [...(exceptions[group.id] ?? []), change.ref] })} />{change.ref}</label><Button size="sm" variant="ghost" onClick={() => onLocate(change.ref)}>목차·원문으로 이동</Button><p>변경 전 {change.before.isHeading ? `L${change.before.level} / 부모 ${change.before.parentRef || '최상위'}` : '비제목/미확정'} → 제안 {change.after.isHeading ? `L${change.after.level} / 부모 ${change.after.parentRef || '최상위'}` : '비제목/보류'} · 절 번호 {change.before.sectionNumber || '없음'} → {change.after.sectionNumber || '없음'}</p></div>)}<Button size="sm" disabled={dirty || job.stale || job.revision !== revision} onClick={() => void approve(group)}>선택 추천 승인 · 초안 반영</Button></details>)}
  </details>;
}
