import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import type { RoleReviewHandle } from './role-review';
import type { ConnectionLink, DocumentInfo, PageBoundary, ReadingDraft, ReadingOccurrence, ReadingScope, Review, RoleElement, TreeDiagnostic } from '@/types';

const names = { normal: '정상', error: '오류 확인', suspected: '의심', unjudgeable: '판단 불가' };
const diagnosticNames = { cycle: '순환 참조', duplicate: '중복 트리 참조', missing: '없는 참조', unreachable: '루트에서 도달 불가' };
const regions = { header: '머리말', footer: '꼬리말', body: '본문', footnote: '각주', table: '표 내부', picture: '그림 내부', unknown: '영역 미확정' };
const blank = (): ReadingDraft => ({ status: '', reason: '', followUp: '', evidence: 'json', order: [], links: [], noConnection: false });
type Props = { document: DocumentInfo; review: Review; busy: boolean; onDirty: (dirty: boolean, valid: boolean) => void; onNavigate: (action: () => Promise<void>) => void; onMutate: (url: string, payload: object) => Promise<boolean>; onEnlarge: (page: number) => void; stageNote: string; onNote: (value: string) => void; stageDirty: boolean; onStage: (action: 'save_note' | 'complete' | 'reopen') => Promise<boolean> };
type Context = { scopes: ReadingScope[]; boundaries: PageBoundary[]; items: RoleElement[]; diagnostics: TreeDiagnostic[]; sourceHash: string; ruleHash: string };
export const ReadingReview = forwardRef<RoleReviewHandle, Props>(function ReadingReview({ document, review, busy, onDirty, onNavigate, onMutate, onEnlarge, stageNote, onNote, stageDirty, onStage }, ref) {
  const [data, setData] = useState<Context | null>(null), [error, setError] = useState('');
  const [mode, setMode] = useState<'order' | 'boundary'>('order'), [targetId, setTargetId] = useState(''), [selectedOccurrence, setSelectedOccurrence] = useState('');
  const [draft, setDraft] = useState<ReadingDraft>(blank), [baseline, setBaseline] = useState('');
  const currentSelection = useRef({ mode, targetId }); currentSelection.current = { mode, targetId };
  const scope = data?.scopes.find(scope => scope.id === targetId), boundary = data?.boundaries.find(boundary => boundary.id === targetId);
  const target = mode === 'order' ? scope : boundary;
  const itemMap = new Map(data?.items.map(item => [item.ref, item]));
  const dirty = !!baseline && JSON.stringify(draft) !== baseline;
  const imagePages = mode === 'order' ? [scope?.page ?? 0] : [boundary?.leftPage ?? 0, boundary?.rightPage ?? 0];
  const imageAvailable = imagePages.every(page => document.pages.find(item => item.number === page)?.imageAvailable);
  const valid = !!target && !!draft.status && !!draft.reason.trim() && (!['suspected', 'unjudgeable'].includes(draft.status) || !!draft.followUp.trim()) && (draft.evidence === 'json' || imageAvailable) && (!['normal', 'error'].includes(draft.status) || !target.pendingRefs.length) && (mode === 'order' ? (draft.status !== 'normal' || !!scope?.sourceOrderKnown && JSON.stringify(draft.order) === JSON.stringify(scope.originalOrder)) && (!['normal', 'error'].includes(draft.status) || !!scope?.page) : (draft.noConnection || draft.links.length > 0 || draft.status === 'unjudgeable') && draft.links.every(link => link.from && link.to && (!['normal', 'error'].includes(draft.status) || link.relation !== 'unknown')));
  function reset(value: ReadingDraft) { setDraft(value); setBaseline(JSON.stringify(value)); onDirty(false, false); }
  function choose(nextMode: 'order' | 'boundary', id: string, context: Context = data!) {
    setMode(nextMode); setTargetId(id);
    if (nextMode === 'order') {
      const scope = context.scopes.find(scope => scope.id === id), row = review.orderReviews.find(row => row.id === id);
      reset({ ...blank(), ...(row ? { status: row.status, reason: row.reason, followUp: row.followUp, evidence: row.evidence, order: [...row.order] } : { order: [...(scope?.originalOrder ?? [])] }) });
      setSelectedOccurrence(scope?.originalOrder[0] ?? '');
    } else {
      const row = review.boundaryReviews.find(row => row.id === id);
      reset({ ...blank(), ...(row ? { status: row.status, reason: row.reason, followUp: row.followUp, evidence: row.evidence, links: row.links.map(link => ({ ...link })), noConnection: row.noConnection } : {}) });
      setSelectedOccurrence('');
    }
  }
  useEffect(() => {
    let active = true;
    void fetch('/api/reading-review').then(async response => { const value: Context & { error?: string } = await response.json(); if (!response.ok) throw new Error(value.error); if (value.sourceHash !== document.sourceHash || value.ruleHash !== document.ruleHash) throw new Error('입력 지문이 바뀌었습니다. 새로고침하세요.'); if (!active) return; setData(value); setError(''); if (!currentSelection.current.targetId) choose('order', value.scopes[0]?.id ?? '', value); }).catch(problem => { if (active) setError(problem.message); });
    return () => { active = false; };
  }, [document.sourceHash, document.ruleHash, review.revision]);
  useEffect(() => { onDirty(dirty, valid); }, [dirty, valid]);
  useEffect(() => () => onDirty(false, false), []);
  function discard() { if (baseline) { setDraft(JSON.parse(baseline)); onDirty(false, false); } }
  async function save() {
    if (!valid) return false;
    const { status, reason, followUp, evidence } = draft;
    const ok = await onMutate(mode === 'order' ? '/api/review/reading-order' : '/api/review/page-connections', { id: targetId, status, reason, followUp, evidence, ...(mode === 'order' ? { order: draft.order } : { links: draft.links, noConnection: draft.noConnection }) });
    if (ok) { setBaseline(JSON.stringify(draft)); onDirty(false, valid); }
    return ok;
  }
  useImperativeHandle(ref, () => ({ save, discard }));
  const navigate = (action: () => void) => onNavigate(async () => action());
  function move(index: number, delta: number) { const order = [...draft.order]; [order[index], order[index + delta]] = [order[index + delta], order[index]]; setDraft({ ...draft, order }); }
  function updateLink(index: number, value: Partial<ConnectionLink>) { setDraft({ ...draft, links: draft.links.map((link, i) => i === index ? { ...link, ...value } : link) }); }
  const title = (occurrence: ReadingOccurrence) => `${occurrence.ref} · ${itemMap.get(occurrence.ref)?.label ?? ''} · ${(itemMap.get(occurrence.ref)?.text || itemMap.get(occurrence.ref)?.cells[0]?.text || '복합 요소').slice(0, 90)}`;
  const c = review.readingCoverage, roleCoverage = review.roleCoverage;
  const ready = !c.unsettledPages.length && !c.unreviewed && !c.needsReview && !c.suspected && !c.dependencyPending && !roleCoverage.unreviewed && !roleCoverage.needsReview && !roleCoverage.suspected;
  const stage = review.stages.find(stage => stage.id === 4)!;
  function sourcePanel(pageNo: number, entries: ReadingOccurrence[], order?: string[]) {
    const page = document.pages.find(page => page.number === pageNo), chosen = entries.find(entry => entry.id === selectedOccurrence);
    return <section className="reading-page" aria-label={`대조 원본 ${pageNo || '출처 없음'}페이지`}><strong>{pageNo ? `원본 ${pageNo}페이지` : '출처 정보 없음'}</strong><div className="role-image-wrap">{page?.imageAvailable ? <><img className="role-page-image" src={page.imageUrl} alt={`순서 대조 원본 ${pageNo}페이지`} />{entries.filter(entry => entry.rect && (mode === 'order' || draft.links.some(link => [link.from, link.to].includes(entry.id)))).map(entry => <div className={`reading-box ${entry.id === selectedOccurrence ? 'reading-box-selected' : ''}`} key={entry.id} style={{ left: `${entry.rect!.left * 100}%`, top: `${entry.rect!.top * 100}%`, width: `${entry.rect!.width * 100}%`, height: `${entry.rect!.height * 100}%` }}><span>{order ? order.indexOf(entry.id) + 1 : '연결'}</span></div>)}</> : <p className="role-no-image">이미지·출처 정보가 없습니다. 위치나 순서를 추정하지 않습니다.</p>}</div>{page?.imageAvailable && <Button size="sm" variant="outline" onClick={() => onEnlarge(pageNo)}>원본 {pageNo}페이지 확대</Button>}{chosen && <div className="role-original"><strong>{chosen.id}</strong><p>영역 {scope ? regions[scope.region] : '연결 대조'} · 원본 소속 {itemMap.get(chosen.ref)?.parentRef || '없음'} · 잠정 소속 {review.roleReviews.find(row => row.ref === chosen.ref)?.parentRef || itemMap.get(chosen.ref)?.parentRef || '미확정'}</p><p className="role-original-text">{itemMap.get(chosen.ref)?.text || itemMap.get(chosen.ref)?.cells.map(cell => cell.text).join('\n') || '텍스트 없는 요소'}</p><details><summary>orig와 모든 원본 출처</summary><pre>{JSON.stringify({ orig: itemMap.get(chosen.ref)?.orig, provenance: itemMap.get(chosen.ref)?.provenance }, null, 2)}</pre></details></div>}</section>;
  }
  if (!data) return <p role={error ? 'alert' : 'status'}>{error || '읽기 순서와 페이지 경계를 읽고 있습니다…'}</p>;
  return <section className="reading-review" aria-label="읽기 순서와 페이지 연결 검수">
    <div className="role-toolbar"><Button size="sm" variant={mode === 'order' ? 'default' : 'outline'} onClick={() => navigate(() => choose('order', data.scopes[0]?.id ?? ''))}>영역 안 읽기 순서</Button><Button size="sm" variant={mode === 'boundary' ? 'default' : 'outline'} onClick={() => navigate(() => choose('boundary', data.boundaries[0]?.id ?? ''))}>페이지 경계 연결</Button><span>영역 {c.scopes} · 경계 {c.boundaries} · 기록 {c.reviewed} · 미검수 {c.unreviewed} · 재검토 {c.needsReview} · 의심 {c.suspected}</span></div>
    <p className="role-scope-note">원본 트리 순서와 영역·소속 판단을 대조합니다. 좌표나 페이지 번호만으로 순서·이어짐을 자동 확정하지 않습니다. 저장은 검수 기록이며 원본 순서와 텍스트를 바꾸지 않습니다.</p>
    {error && <p role="alert">{error}</p>}
    {!!data.diagnostics.length && <details className="reading-diagnostics"><summary>원본 트리 진단 {data.diagnostics.length}건 · 순환/중복/없는 참조/도달 불가</summary><ul>{data.diagnostics.map((issue, index) => <li key={index}>{diagnosticNames[issue.kind]} · {issue.ref || '참조 없음'} · 부모 {issue.parentRef || '없음'}<p>경로 {issue.path.join(' → ') || '루트 경로 없음'}{issue.firstPath ? ` · 첫 경로 ${issue.firstPath.join(' → ')}` : ''}</p><p>영향 대상: {issue.affectedRefs.join(', ') || '연결할 요소를 알 수 없음'}</p></li>)}</ul></details>}
    {!!scope?.diagnostics.length && mode === 'order' && <p className="restore-hint">현재 영역의 원본 순서는 트리 진단 {scope.diagnostics.length}건의 영향을 받습니다. 누락 순서를 추정하지 않으며 정상 확정을 제한합니다.</p>}
    <label className="role-group-picker">{mode === 'order' ? '영역·소속 선택' : '유지 페이지 경계 선택'}<select aria-label={mode === 'order' ? '영역·소속 선택' : '유지 페이지 경계 선택'} value={targetId} disabled={busy} onChange={event => navigate(() => choose(mode, event.target.value))}>{!target && <option value={targetId}>현재 대상 없음 · 대상을 선택하세요</option>}{mode === 'order' ? data.scopes.map(scope => <option value={scope.id} key={scope.id}>{scope.page ? `원본 ${scope.page}페이지` : '출처 없음'} · {regions[scope.region]} · {scope.parentRef || '소속 없음'} · {scope.entries.length}개 출처</option>) : data.boundaries.map(boundary => <option value={boundary.id} key={boundary.id}>원본 {boundary.leftPage} → {boundary.rightPage}페이지{boundary.skippedPages.length ? ` · 제외 ${boundary.skippedPages.join(', ')}` : ''}</option>)}</select></label>
    {target?.pendingRefs.length ? <p className="restore-hint">관련 영역·역할·소속 미확정 {target.pendingRefs.length}개. 독립 검토는 의심·판단 불가로 기록하고 정상·오류 확정 전에 관련 판단을 확인하세요.</p> : null}
    {(mode === 'order' ? review.orderReviews : review.boundaryReviews).find(row => row.id === targetId)?.needsReview && <p className="restore-hint">영역·소속 또는 페이지 범위가 바뀌었습니다. 이 대상을 다시 대조하고 저장하세요.</p>}
    {mode === 'order' && scope && <div className="role-workbench">{sourcePanel(scope.page, scope.entries, draft.order)}<section className="reading-sequence" aria-label="순서안 편집"><h2>{scope.sourceOrderKnown ? '원본 트리 순서 → 검토 순서안' : '출처 목록 → 검토 순서안'}</h2><p className="role-scope-note">모든 출처 {scope.entries.length}개를 유지합니다. 번호는 검토 순서안이며 원본 트리를 변경하지 않습니다.</p>{!scope.sourceOrderKnown && <p className="restore-hint">원본 트리 진단으로 순서가 미확정입니다. 현재 표시 목록은 출처를 빠짐없이 보여주기 위한 것으로, 누락된 원본 순서를 추정한 결과가 아닙니다.</p>}<Button size="sm" variant="outline" disabled={busy} onClick={() => setDraft({ ...draft, order: [...scope.originalOrder] })}>{scope.sourceOrderKnown ? '원본 순서로 초안 복원' : '표시 목록으로 초안 되돌림'}</Button><ol className="reading-order-list">{draft.order.map((id, index) => { const entry = scope.entries.find(entry => entry.id === id); return <li key={id}><Button className="reading-entry" variant={selectedOccurrence === id ? 'secondary' : 'ghost'} disabled={busy} aria-label={`순서 ${index + 1} 출처 ${id} 선택`} onClick={() => setSelectedOccurrence(id)}>{index + 1}. {entry ? title(entry) : `범위 변경 ${id}`}</Button><span className="reading-original-index">{entry?.sourceIndex === null ? '원본 순서 미확정' : `원본 ${scope.originalOrder.indexOf(id) + 1 || '없음'}`}</span><Button size="sm" variant="outline" disabled={busy || index === 0} aria-label={`${id} 위로 이동`} onClick={() => move(index, -1)}>↑</Button><Button size="sm" variant="outline" disabled={busy || index === draft.order.length - 1} aria-label={`${id} 아래로 이동`} onClick={() => move(index, 1)}>↓</Button></li>; })}</ol></section></div>}
    {mode === 'boundary' && boundary && <><p className="role-scope-note">원본 {boundary.leftPage} → {boundary.rightPage}페이지 대조{boundary.skippedPages.length ? ` · 사이에서 제외한 원본 페이지: ${boundary.skippedPages.join(', ')}` : ''}. 제외 간격을 이어짐으로 자동 판단하지 않습니다.</p><div className="reading-page-pair">{sourcePanel(boundary.leftPage, boundary.leftEntries)}{sourcePanel(boundary.rightPage, boundary.rightEntries)}</div><section className="reading-links" aria-label="페이지 경계 연결안"><h2>문단·표·각주 연결안</h2><label className="reading-none"><input type="checkbox" checked={draft.noConnection} disabled={busy} onChange={event => setDraft({ ...draft, noConnection: event.target.checked, links: event.target.checked ? [] : draft.links })} />양쪽 경계를 확인했고 연결할 항목 없음</label>{draft.links.map((link, index) => <div className="reading-link" key={index}><label>앞 페이지 출처<select aria-label={`연결 ${index + 1} 앞 출처`} value={link.from} disabled={busy} onChange={event => { updateLink(index, { from: event.target.value }); setSelectedOccurrence(event.target.value); }}><option value="">대상 선택</option>{boundary.leftEntries.map(entry => <option key={entry.id} value={entry.id}>{title(entry)}</option>)}</select></label><label>뒤 페이지 출처<select aria-label={`연결 ${index + 1} 뒤 출처`} value={link.to} disabled={busy} onChange={event => { updateLink(index, { to: event.target.value }); setSelectedOccurrence(event.target.value); }}><option value="">대상 선택</option>{boundary.rightEntries.map(entry => <option key={entry.id} value={entry.id}>{title(entry)}</option>)}</select></label><label>내용 유형<select aria-label={`연결 ${index + 1} 내용 유형`} value={link.kind} disabled={busy} onChange={event => updateLink(index, { kind: event.target.value as ConnectionLink['kind'] })}><option value="paragraph">문단</option><option value="table">표</option><option value="footnote">각주</option><option value="other">기타</option></select></label><label>관계<select aria-label={`연결 ${index + 1} 관계`} value={link.relation} disabled={busy} onChange={event => updateLink(index, { relation: event.target.value as ConnectionLink['relation'] })}><option value="unknown">미확정</option><option value="continuation">이어짐</option><option value="separate">별개</option><option value="related">관련</option></select></label><Button size="sm" variant="outline" disabled={busy} aria-label={`연결 ${index + 1} 초안 제거`} onClick={() => setDraft({ ...draft, links: draft.links.filter((_, i) => i !== index) })}>항목 제거</Button></div>)}<Button size="sm" variant="outline" disabled={busy || !boundary.leftEntries.length || !boundary.rightEntries.length} onClick={() => setDraft({ ...draft, noConnection: false, links: [...draft.links, { from: '', to: '', kind: 'paragraph', relation: 'unknown' }] })}>연결 항목 추가</Button></section></>}
    {target && <section className="reading-judgment" aria-label="순서·연결 판단"><label className="field-label" htmlFor="reading-status">순서·연결 검수 판단</label><select id="reading-status" value={draft.status} disabled={busy} onChange={event => setDraft({ ...draft, status: event.target.value as ReadingDraft['status'] })}><option value="">판단 선택</option>{Object.entries(names).map(([key, name]) => <option key={key} value={key} disabled={['normal', 'error'].includes(key) && !!target.pendingRefs.length || key === 'normal' && mode === 'order' && !scope?.sourceOrderKnown}>{name}</option>)}</select><label className="field-label" htmlFor="reading-reason">순서·연결 근거·사유 · 필수</label><Textarea id="reading-reason" value={draft.reason} maxLength={10000} disabled={busy} onChange={event => setDraft({ ...draft, reason: event.target.value })} /><label className="field-label" htmlFor="reading-evidence">순서·연결 대조 근거</label><select id="reading-evidence" value={draft.evidence} disabled={busy} onChange={event => setDraft({ ...draft, evidence: event.target.value as ReadingDraft['evidence'] })}><option value="json">JSON 내부 근거</option><option value="page_image" disabled={!imageAvailable}>원문 페이지 이미지</option><option value="both" disabled={!imageAvailable}>이미지 + JSON</option></select><label className="field-label" htmlFor="reading-followup">순서·연결 후속 확인{['suspected', 'unjudgeable'].includes(draft.status) ? ' · 필수' : ''}</label><Textarea id="reading-followup" value={draft.followUp} maxLength={10000} disabled={busy} onChange={event => setDraft({ ...draft, followUp: event.target.value })} /><div className="record-actions"><Button variant="outline" disabled={busy || !dirty} onClick={discard}>순서·연결 초안 취소</Button><Button disabled={busy || !dirty || !valid} onClick={() => void save()}>{mode === 'order' ? '영역 순서 판단 저장' : '페이지 연결 판단 저장'}</Button></div></section>}
    <section className="role-completion"><h2>읽기 순서·페이지 연결 검수 완료</h2><p>전체 유지 범위와 관련 영역 판단을 확인해야 합니다. 미검수·재검토·의심은 남겨 둔 채 완료하지 않습니다.</p><label className="field-label" htmlFor="stage-note">읽기 순서·연결 전체 범위와 미확인 사항</label><Textarea id="stage-note" value={stageNote} maxLength={10000} disabled={busy} onChange={event => onNote(event.target.value)} /><div className="record-actions"><Button variant="outline" disabled={busy || !stageDirty} onClick={() => onNote(stage.note)}>메모 초안 취소</Button><Button variant="outline" disabled={busy || dirty || !stageDirty} onClick={() => void onStage('save_note')}>메모 저장</Button><Button disabled={busy || dirty || !stageNote.trim() || (stage.status !== 'completed' && !ready)} onClick={() => void onStage(stage.status === 'completed' ? 'reopen' : 'complete')}>{stage.status === 'completed' ? '완료 취소' : '읽기 순서·연결 완료 기록'}</Button></div></section>
  </section>;
});
